services:
  spring-server:
    image: bookgle:1
    networks:
      - bookgle
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always

  nginx:
    image: nginx:1
    ports:
      - 80:80
    networks:
      - bookgle
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - spring-server
    restart: always

networks:
  bookgle:
    driver: bridge