services:
  spring-server:
    image: bookgle:1
    networks:
      - bookgle
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx:1
    ports:
      - 80:80
    networks:
      - bookgle
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - spring-server
    restart: always

  mariadb:
    image: mariadb:1
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - 3306:3306
    networks:
      - bookgle
    volumes:
      - bookgle_db:/var/lib/mysql
volumes:
    bookgle_db:

networks:
  bookgle:
    driver: bridge