services:
  spring-server:
    image: noel95/bookgle:spring-server
#    image: bookgle:1
    networks:
      - bookgle
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    platform: linux/amd64

  nginx:
    image: noel95/bookgle:nginx
#    image: nginx:1
    ports:
      - 80:80
    networks:
      - bookgle
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - spring-server
    restart: always
    platform: linux/amd64

  mariadb:
    image: noel95/bookgle:mariadb
#    image: mariadb:1
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p$DB_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookgle
    volumes:
      - bookgle_db:/var/lib/mysql
    platform: linux/amd64

volumes:
    bookgle_db:

networks:
  bookgle:
    driver: bridge