services:
  spring-server${COMMIT_HASH}:
    env_file:
      - .env
    image: ${DOCKER_USERNAME}/bookgle:spring-server
    networks:
      - bookgle
    restart: always

  nginx${COMMIT_HASH}:
    env_file:
      - .env
    image: ${DOCKER_USERNAME}/bookgle:nginx
    ports:
      - 80:80
    networks:
      - bookgle
    depends_on:
      - spring-server${COMMIT_HASH}
    restart: always

networks:
  bookgle:
    driver: bridge