services:
  spring-server:
    image: bookgle:1
    networks:
      - bookgle
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always

  nginx:
    image: nginx:1
    ports:
      - 80:80
    networks:
      - bookgle
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - spring-server
    restart: always

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: testDB
      MYSQL_USER: testUser
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    networks:
      - bookgle
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:

networks:
  bookgle:
    driver: bridge