services:
  spring-server-${COMMIT_HASH}:
    image: ${DOCKER_USERNAME}/bookgle:spring-server
    # image: bookgle:1
    networks:
      - bookgle
    restart: always

  nginx-${COMMIT_HASH}:
    image: ${DOCKER_USERNAME}/bookgle:nginx
    # image: nginx:1
    ports:
      - 80:80
    networks:
      - bookgle
    depends_on:
      - spring-server-${COMMIT_HASH}
    restart: always

networks:
  bookgle:
    driver: bridge