services:
  spring-server-${COMMIT_HASH}:
    image: ${DOCKER_USERNAME}/bookgle:spring-server
    # image: bookgle:1
    networks:
      - bookgle
    build:
      # context: ./backend
      context: .
      dockerfile: backend/Dockerfile
    restart: always

  nginx-${COMMIT_HASH}:
    image: ${DOCKER_USERNAME}/bookgle:nginx
    # image: nginx:1
    ports:
      - 80:80
    networks:
      - bookgle
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - spring-server
    restart: always

networks:
  bookgle:
    driver: bridge