name: backend CI

on:
  push:
    branches: [main] # main 브랜치에 push 이벤트 발생 시 실행

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/config/"
      
    steps:
      # - name: SSH Key 설정
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.BACKEND_CONFIG_PRIVATE_KEY }} # Github Secrets에 저장된 SSH Key

      - name: Setup SSH key to access private submodule
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.BACKEND_CONFIG_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - uses: actions/checkout@v3
        with:
          submodules: true # 서브모듈 checkout
          ssh-key: ${{ secrets.BACKEND_CONFIG_PRIVATE_KEY }}

      - name: Update config submodule
        run: |
          git submodule update --init

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: "17"
            distribution: "corretto"
            
      - name: Build with Gradle
        run: |
          cd backend
          chmod +x gradlew
          ./gradlew build
        shell: bash

      # - name: 배포 (필요시)
      #   run: ...
