name: backend CI

on:
  push:
    branches: [main] # main 브랜치에 push 이벤트 발생 시 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Spring Config Location
        run: echo "SPRING_CONFIG_ADDITIONAL_LOCATION=file:${{ github.workspace }}/config/" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          submodules: true # 서브모듈 checkout
          ssh-key: ${{ secrets.BACKEND_CONFIG_PRIVATE_KEY }}

      - name: Update config submodule
        run: |
          git submodule update --init

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: "17"
            distribution: "corretto"
            
      - name: Build with Gradle
        run: |
          cd backend
          chmod +x gradlew
          ./gradlew build
        shell: bash
        
